<br>
<br>

## <b style='color:red;'> 본 실습 파일은 SNUCTL 강의를 위해 제작되었으며, 본 교육 外 배포/게시/공개를 금합니다.</p>

<br>
<br>

<br>

#### 0. 특정 함수에 대해 궁금할 때

In [1]:
help(print)

Help on built-in function print in module builtins:

print(...)
    print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)
    
    Prints the values to a stream, or to sys.stdout by default.
    Optional keyword arguments:
    file:  a file-like object (stream); defaults to the current sys.stdout.
    sep:   string inserted between values, default a space.
    end:   string appended after the last value, default a newline.
    flush: whether to forcibly flush the stream.



In [2]:
print() # Shift+Tap

In [117]:
# 이것은 주석입니다.

<br>

#### 1. 기초 데이터 타입

#### 정수형(integer)과 실수형(floats)

In [3]:
x = 3

In [4]:
x

3

In [5]:
type(x)

int

In [6]:
x+1

4

In [7]:
x*2

6

In [8]:
x**2

9

In [9]:
x += 1
x

4

In [10]:
x *= 2
x

8

In [11]:
y = 2.5

In [12]:
type(2.5)

float

In [13]:
print(y, y+1, y*2, y**2)

2.5 3.5 5.0 6.25


In [14]:
x = 9

In [15]:
x / 2 # 몫, 소수점까지 계산

4.5

In [16]:
x // 2 # 몫, 정수로만 계산

4

In [17]:
x % 2 # 나머지

1

In [18]:
x = 9 
float(x)

9.0

In [19]:
x = 3.14
int(x)

3

#### 문자열 (string)

In [20]:
s = "Hello"

In [21]:
print(s)
print(type(s))

Hello
<class 'str'>


In [22]:
len(s)

5

In [23]:
s.upper()

'HELLO'

In [24]:
s.lower()

'hello'

In [25]:
print("My name is {}".format("Groot"))

My name is Groot


In [26]:
print("My name is {} and I'm {} years old".format("Groot", 99))

My name is Groot and I'm 99 years old


In [27]:
print("Hello" + " " + "world")

Hello world


In [28]:
temp = "Python"

In [29]:
temp[0]

'P'

In [30]:
temp[0:4]

'Pyth'

In [31]:
temp = "Python is easy"
temp.split()

['Python', 'is', 'easy']

In [32]:
temp = "Python, is, easy"
temp.split(",")

['Python', ' is', ' easy']

In [33]:
temp = ['Python', 'is', 'easy']
'#'.join(temp)

'Python#is#easy'

In [34]:
' '.join(temp)

'Python is easy'

In [35]:
x = 214
str(x)

'214'

#### 참/거짓 (bool)

In [36]:
t = True
f = False

In [37]:
print(type(t))

<class 'bool'>


In [38]:
print(t and f)

False


In [39]:
print(t or f)

True


In [40]:
print(not t)

False


In [41]:
t = 1
f = 0

In [42]:
print(t and f)

0


In [43]:
t == True

True

<br>

#### 2. 함수 (function, method)

In [44]:
def just_print():
    print("Yes, I'm groot")

In [45]:
just_print()

Yes, I'm groot


In [46]:
def add_nums(x, y):
    print(x+y)

In [47]:
add_nums(2, 3)

5


In [48]:
def add_nums(x, y):
    return x+y

In [49]:
a = add_nums(3, 4)

In [50]:
a

7

In [51]:
# Quiz 1. 성과 이름을 받아 이름을 출력해주는 함수 name_creater 만들기

def name_creater(last, first):
    print(last + first)

In [52]:
name_creater("그", "루트")

그루트


In [53]:
# Quiz 2. 다음 함수는 에러를 출력합니다. 어디를 고쳐야할까요?
def drink():
beverage = "Coke"
print(beverage)

IndentationError: expected an indented block (<ipython-input-53-15cfe17b83f7>, line 3)

In [54]:
# Quiz 3. 원의 반지름을 받아 원의 넓이를 Return 해주는 함수 circle_area 만들기 (ㅠ = 3.14)
def circle_area(r):
    return r ** 2 * 3.14

In [55]:
circle_area(10)

314.0

<br>

#### 3. 컨테이너 (다른 변수들을 담을 수 있는 자료형)
list, dict, tuple, set

#### 리스트 (list)

In [56]:
x = [3, 1, 2, 4, 6]
x

[3, 1, 2, 4, 6]

In [57]:
x[0]

3

In [58]:
x[0:3]

[3, 1, 2]

In [59]:
x[1:]

[1, 2, 4, 6]

In [60]:
x[-1]

6

In [61]:
x.append("어머나")
x

[3, 1, 2, 4, 6, '어머나']

In [62]:
x.pop() # 리스트의 마지막 요소를 삭제하고 반환

'어머나'

In [63]:
x

[3, 1, 2, 4, 6]

In [147]:
# 리스트 아이템의 삭제 
# 1) 데이터의 순서/자리를 활용하여 삭제할 때 : del == index를 활용
# 2) 데이터 값 자체를 활용하여 삭제할 때 : remove() == value를 활용

In [64]:
del x[0]
x

[1, 2, 4, 6]

In [65]:
x.remove(4)
x

[1, 2, 6]

In [66]:
# 리스트 합치기
y = [3, 4, 5]
z = x+y
z

[1, 2, 6, 3, 4, 5]

In [67]:
# 리스트 정렬하기
z.sort()
z

[1, 2, 3, 4, 5, 6]

In [68]:
# 리스트 역으로 정렬하기
z.sort(reverse=True)
z

[6, 5, 4, 3, 2, 1]

#### 딕셔너리 (dict)

In [1]:
cage = {'Cat' : '야옹', 'Dog' : '멍멍'}
cage

{'Cat': '야옹', 'Dog': '멍멍'}

In [70]:
cage['Cat']

'야옹'

In [2]:
cage.get('Cat')

'야옹'

In [4]:
cage.get('Fish', '집나감')

'집나감'

In [71]:
print('Pig' in cage)

False


In [72]:
cage['Pig'] = '꿀꿀'
cage

{'Cat': '야옹', 'Dog': '멍멍', 'Pig': '꿀꿀'}

In [73]:
del cage['Pig']
cage

{'Cat': '야옹', 'Dog': '멍멍'}

In [74]:
cage.keys()

dict_keys(['Cat', 'Dog'])

In [75]:
cage.values()

dict_values(['야옹', '멍멍'])

In [76]:
# list -> dict

temp = [['Cat', '야옹'], ['Dog', '멍멍'], ['Tiger', '어흥']]
cage = dict(temp)
cage

{'Cat': '야옹', 'Dog': '멍멍', 'Tiger': '어흥'}

#### 튜플(tuple) 
값과 크기가 변하지 않음

In [77]:
t = (5, 6)
type(t)

tuple

In [78]:
t[0]

5

In [79]:
def return_tuple(x, y):
    return x, y

In [80]:
what = return_tuple(3, 4)
what

(3, 4)

#### 집합(set)
중복을 허용하지 않음

In [81]:
s = {1, 2, 3, 3, 4, 4, 5}
s

{1, 2, 3, 4, 5}

In [82]:
temp = [1, 2, 3, 3, 4, 4, 5]
temp

[1, 2, 3, 3, 4, 4, 5]

In [83]:
what = list(set(temp))
what

[1, 2, 3, 4, 5]

<br>

#### 4. 조건문과 반복문
if, for, while

#### if

In [84]:
x = 'Groot'

In [85]:
if x == 'Groot':
    print("I'm Groot")

I'm Groot


In [86]:
if x != 'Groot':
    print("I'm groot")

In [87]:
price = 7000

In [88]:
if price > 10000:
    print("거참 창렬일세")
elif price < 3000:
    print("와우 혜자다 혜자")
else:
    print("얼른 벌어서 소고기 먹어야지")

얼른 벌어서 소고기 먹어야지


In [89]:
cage = ['Cat', 'Dog', 'Tiger']

In [90]:
if 'Cat' in cage:
    print('야옹아 이리온')

야옹아 이리온


In [91]:
cage = {'Cat': '야옹', 'Dog': '멍멍', 'Tiger': '어흥'}

In [92]:
if 'Dog' in cage.keys():
    print('치와와는 언제와')

치와와는 언제와


In [93]:
number = 100

In [94]:
if 99 is not number:
    print("100점을 못 받았어 ㅠㅠ")

100점을 못 받았어 ㅠㅠ


#### for

In [95]:
nums = [1, 2, 3, 4, 5]

In [96]:
for number in nums:
    print(number)

1
2
3
4
5


In [97]:
range(5)

range(0, 5)

In [98]:
for index in range(5):
    print(index)

0
1
2
3
4


In [99]:
cage = {'Cat': '야옹', 'Dog': '멍멍', 'Tiger': '어흥'}

In [100]:
for item in cage.items():
    print(item)

('Tiger', '어흥')
('Cat', '야옹')
('Dog', '멍멍')


In [101]:
class = ['철수', '영희', '동수'] # 왜 에러가 발생할까요?

SyntaxError: invalid syntax (<ipython-input-101-1c5ef2a21299>, line 1)

In [102]:
class_1 = ['철수', '영희', '동수']

In [103]:
for index, student in enumerate(class_1):
    print("얘 번호는 {}번이구요. 이름은 {}래요".format(index+1, student))

얘 번호는 1번이구요. 이름은 철수래요
얘 번호는 2번이구요. 이름은 영희래요
얘 번호는 3번이구요. 이름은 동수래요


In [104]:
empty_list = []
for student in class_1:
    empty_list.append(student)

In [105]:
empty_list

['철수', '영희', '동수']

#### while

In [106]:
temp = 1
while temp <= 10:
    print(temp)
    temp += 1

1
2
3
4
5
6
7
8
9
10


In [107]:
# 무한 루프, Pass, Interrupting kernel

while True:
    pass

KeyboardInterrupt: 

In [212]:
# Quiz 4. 점수(0~100)를 입력으로 받아 학점을 출력해주는 함수 grade를 만드세요.

In [213]:
def grade(score):
    if score > 90:
        print('A')
    elif score > 80:
        print('B')
    elif score > 70:
        print('C')
    else:
        print("F")

In [215]:
grade(87)

B


In [216]:
# Quiz 5. 3개의 숫자를 입력으로 받아, 가장 큰 수를 출력하는 함수 best 를 만드세요. (Hint. 리스트와 sort()를 활용해보세요.)

In [241]:
def best(a, b, c):
    temp = [a, b, c]
    temp.sort(reverse=True)
    print(temp[0])

In [242]:
best(20, 80, 100)

100


In [251]:
# Quiz 6. 숫자 하나를 입력받아, 홀수면 "odd", 짝수면 "even"을 출력하는 함수 odd_or_even을 만드세요. (나머지 연산 명령어는?)

In [252]:
def odd_or_even(x):
    if x % 2 == 0:
        print("even")
    elif x % 2 == 1:
        print("odd")

In [253]:
odd_or_even(9)

odd


In [254]:
# Quiz 7. "20180323sunny" 와 같은 문자열을 입력받아, "Year is 2018, Day is 0323, Weather is sunny" 를 출력하는 함수 weather를 만드세요.

In [255]:
def weather(string):
    print("Year is {}, Day is {}, Weather is {}".format(string[0:4], string[4:8], string[8:]))

In [256]:
weather('20180323still cold')

Year is 2018, Day is 0323, Weather is still cold


<br>

#### 5. 파일 읽고 쓰기

#### 파일 쓰기

In [108]:
file = open('cage.txt', 'w', encoding='utf-8')

In [109]:
cage = ['Cat', 'Dog', 'Tiger']

In [110]:
file.write(cage) # 에러가 발생했어요. 어떻게 해야할까요?

TypeError: write() argument must be str, not list

In [111]:
for animal in cage:
    file.write(animal)

In [112]:
file.close()

In [113]:
file = open('cage.txt', 'w', encoding='utf-8')

In [114]:
for animal in cage:
    file.write(animal + '\n')

In [115]:
file.close()

In [116]:
# with 과 함께 쓰기

with open('cage.txt', 'w', encoding='utf-8') as file:
    for animal in cage:
        file.write(animal + '\n')

#### 파일 읽기

In [117]:
file = open('cage.txt', 'r', encoding='utf-8')

In [118]:
cage = file.readlines()
cage

['Cat\n', 'Dog\n', 'Tiger\n']

In [119]:
print(cage[0])

Cat



<br>

#### 6. Python 기본 내장함수와 외장함수

In [311]:
len('Python')

6

In [312]:
list('Python')

['P', 'y', 't', 'h', 'o', 'n']

In [313]:
abs(-1.2)

1.2

In [322]:
round(1.7)

2

In [314]:
bool(1)

True

In [317]:
sum([1, 2, 3])

6

In [318]:
max([1, 2, 3])

3

In [319]:
min([1, 2, 3])

1

In [321]:
list(range(0, 100, 10))

[0, 10, 20, 30, 40, 50, 60, 70, 80, 90]

In [144]:
def func(x):
    return x**2

In [145]:
func(5)

25

In [323]:
func = lambda x: x**2

In [324]:
func(5)

25

In [325]:
import random # 외장함수

x = random.random()
x

0.10961064046566416

In [326]:
x = random.randint(1, 100)
x

7

In [ ]:
import os # 외장함수

os.getcwd()

<br>

#### 7. 라이브러리 활용하기 (Library == Package, Module(단일 .py)의 상위 개념 )

In [337]:
import numpy # import 라이브러리이름

In [338]:
a = numpy.array([1, 2, 3])
a

array([1, 2, 3])

In [339]:
import numpy as np # import 라이브러리이름 as 별명

In [340]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [343]:
from numpy import array, ndarray # from 라이브러리이름 import 함수이름

In [342]:
a = array([1, 2, 3])
a

array([1, 2, 3])