<br>
<br>

## <b style='color:red;'> 본 실습 파일은 SNUCTL 강의를 위해 제작되었으며, 본 교육 外 배포/게시/공개를 금합니다.</p>

<br>
<br>

<br>

#### 0. 특정 함수에 대해 궁금할 때

In [2]:
# Shift + Enter : 셀의 실행
# Shift + Tap : 함수 & 변수의 Docstring 확인

print() 

Help on built-in function print in module builtins:

print(...)
    print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)
    
    Prints the values to a stream, or to sys.stdout by default.
    Optional keyword arguments:
    file:  a file-like object (stream); defaults to the current sys.stdout.
    sep:   string inserted between values, default a space.
    end:   string appended after the last value, default a newline.
    flush: whether to forcibly flush the stream.



In [3]:
# 이것은 주석입니다.

<br>

#### 1. 기초 데이터 타입

#### 정수형(integer)과 실수형(floats)

In [14]:
x = 9

print(x)

In [5]:
type(x)

int

In [3]:
x + 1

10

In [4]:
x * 2

18

In [5]:
x ? 2 # 제곱 연산

81

In [6]:
x ? 2 # 몫, 소수점까지 계산

4.5

In [16]:
x ? 2 # 몫, 정수로만 계산

4

In [17]:
x ? 2 # 나머지

1

In [7]:
x += 1
x

10

In [8]:
x ? 2 # 곱하여 변수에 그대로 담기
x

20

In [9]:
y = 2.5

In [12]:
?(y) # 어떤 타입일까요?

float

In [10]:
# y를 정수 자료형으로 바꾸려면?
?(y) # from float to integer

2

In [18]:
x = 9 
float(x) 

9.0

In [13]:
print(y, y+1, y*2, y**2)

2.5 3.5 5.0 6.25


In [19]:
x = 3.14
?(x) # from float to integer

3

#### 문자열 (string)

In [11]:
s = "Hello"

In [12]:
type(s)

str

In [22]:
?(s) # 길이를 영어로 하면? (앞 3글자)

5

In [23]:
s.upper()

'HELLO'

In [24]:
s.?() # 모두 소문자로

'hello'

In [25]:
print("My name is {}".format("Groot"))

My name is Groot


In [27]:
print("Hello" ? " " ? "world") # 문자열 합치기

Hello world


In [4]:
temp = "Python"

In [ ]:
temp()
temp[?]

? <-  :
? <-  : 

In [29]:
temp[0]

'P'

In [30]:
temp[0:4]

'Pyth'

In [5]:
temp[4:]

'on'

In [6]:
temp[-1]

'n'

In [31]:
temp = "Python is easy"
temp.split() # str을 특정한 문자(기본값:여백)를 기준으로 잘라내어 list로 만들어줍니다. (이 때 기준이 되는 해당 문자는 삭제됩니다.)

['Python', 'is', 'easy']

In [16]:
temp = "Python is easy"
temp.split(?) # 's'를 기준으로 자르려면?

['Python i', ' ea', 'y']

In [17]:
temp = ['Python', 'is', 'easy']
'___'.join(temp)

'Python___is___easy'

In [34]:
'?'.join(temp) # "Python is easy" 와 같이 합치려면?

'Python is easy'

In [35]:
x = 214
?(x) # Integer to string

'214'

#### 참/거짓 (bool)

In [18]:
t = True
f = False

In [19]:
type(t)

bool

In [38]:
print(t and f)

False


In [39]:
print(t or f)

True


In [40]:
print(not t)

False


<br>

#### 2. 함수 (function, method)

In [46]:
# 2개의 숫자를 외부로부터 받아 합친 값을 돌려주는 함수 add_nums 만들기


In [47]:
add_nums(2, 3)

5


In [51]:
# Quiz 1. 성과 이름을 받아 이름을 출력해주는 함수 name_creator 만들기


In [52]:
name_creator("그", "루트")

그루트


In [53]:
# Quiz 2. 다음 함수는 에러를 출력합니다. 어디를 고쳐야할까요?
def drink():
beverage = "Coke"
print(beverage)

IndentationError: expected an indented block (<ipython-input-53-15cfe17b83f7>, line 3)

In [54]:
# Quiz 3. 원의 반지름을 받아 원의 넓이를 Return 해주는 함수 circle_area 만들기 (ㅠ = 3.14)


In [55]:
circle_area(10)

314.0

<br>
<br>

# <b style='color:gray;'>PAUSE</b>

<br>
<br>

<br>

#### 3. 컨테이너 (다른 변수들을 담을 수 있는 자료형)
list, dict, tuple, set

#### 리스트 (list)

In [4]:
x = [3, 1, 2, 4, 6] # 리스트의 생성
x

[3, 1, 2, 4, 6]

In [57]:
x[0]

3

In [58]:
x[?] # [3, 1, 2] 를 출력하려면?

[3, 1, 2]

In [59]:
x[?] # 1부터 끝까지?

[1, 2, 4, 6]

In [60]:
x[-1] 

6

In [5]:
x.append("어머나") # 리스트 item 추가하기
x

[3, 1, 2, 4, 6, '어머나']

In [6]:
x.pop() # 기본적으로 리스트의 마지막 요소를 삭제하고 반환 (pop(n) -> index 기반으로 n번째 아이템을 삭제할 수도 있음)

'어머나'

In [7]:
x

[3, 1, 2, 4, 6]

In [147]:
# 리스트 아이템의 삭제 
# 1) 데이터의 순서/자리를 활용하여 삭제할 때 : del == index를 활용 (추천)
# 2) 데이터 값 자체를 활용하여 삭제할 때 : remove() == value를 활용
# 3) 삭제 후 삭제한 값을 리턴받아 활용해야할 때 : pop() == index를 활용

In [8]:
? x[0] # 삭제의 영어 단어 앞 3글자? 
x

[1, 2, 4, 6]

In [65]:
x.remove(4)
x

[1, 2, 6]

In [66]:
# 리스트 합치기
y = [3, 4, 5]
z = x ? y # 쉽게 생각해보세요 :)
z

[1, 2, 6, 3, 4, 5]

In [67]:
# 리스트 정렬하기
z.sort()
z

[1, 2, 3, 4, 5, 6]

In [68]:
# 리스트 역으로 정렬하기
z.sort(?=True) # '거꾸로' 를 영어로 하면?
z

[6, 5, 4, 3, 2, 1]

#### 딕셔너리 (dict)

In [1]:
cage = {'Cat' : '야옹', 'Dog' : '멍멍'} # {key:value, key:value, ...}
cage

{'Cat': '야옹', 'Dog': '멍멍'}

In [2]:
cage['Cat'] # key 기반 호출

'야옹'

In [3]:
cage.?('Cat') # '얻다'

'야옹'

In [ ]:
cage.?('Fish', '집나감') # 어떤 결과가 나올까요?

In [71]:
print('Pig' ? cage) # key 유무 체크

False


In [72]:
cage['Pig'] = '꿀꿀' # dict에 새로운 item 추가하기
cage

{'Cat': '야옹', 'Dog': '멍멍', 'Pig': '꿀꿀'}

In [73]:
? cage['Pig'] # 삭제의 영어 단어 앞 3글자?
cage

{'Cat': '야옹', 'Dog': '멍멍'}

In [74]:
cage.keys()

dict_keys(['Cat', 'Dog'])

In [75]:
cage.?() # value들을 꺼내려면?

dict_values(['야옹', '멍멍'])

#### 튜플(tuple) 
값과 크기가 변하지 않음

In [77]:
t = (5, 6)
type(t)

tuple

In [78]:
t[0]

5

In [79]:
# 튜플이 사용되는 예시

def return_tuple(x, y):
    return x, y

In [80]:
what = return_tuple(3, 4)
what

(3, 4)

#### 집합(set)
중복을 허용하지 않음

In [81]:
s = {1, 2, 3, 3, 4, 4, 5} 
s

{1, 2, 3, 4, 5}

In [82]:
temp = [1, 2, 3, 3, 4, 4, 5]
temp

[1, 2, 3, 3, 4, 4, 5]

In [83]:
# 리스트 temp 에서 중복을 제거하고, 다시 리스트로 만드려면?

what = ?(?(temp))
what

[1, 2, 3, 4, 5]

<br>

#### 4. 조건문과 반복문
if, for, while

#### if

In [5]:
def check_price(lunch_price):
    
    price_label = ''
    
    if lunch_price > 10000:
        price_label = "프리미엄 도시락"
    ? lunch_price < 3000: 
        price_label = "저렴이 도시락"
    ?: # 나머지 조건 모두 받기
        price_label = "무난무난 도시락"
        
    return price_label

무난무난 도시락


In [ ]:
check_price(7000)

In [89]:
cage = ['Cat', 'Dog', 'Tiger']

In [90]:
if 'Cat' ? cage:  # Key 유무 체크
    print('야옹아 이리온')

야옹아 이리온


In [91]:
cage = {'Cat': '야옹', 'Dog': '멍멍', 'Tiger': '어흥'}

In [92]:
if 'Dog' ? cage.keys(): # Key 유무 체크
    print('치와와는 언제와')

치와와는 언제와


In [ ]:
if 1:
    print('1 is True')

#### for

In [95]:
nums = [1, 2, 3, 4, 5]

In [96]:
for number in nums:
    print(number)

1
2
3
4
5


In [1]:
cage = {'Cat': '야옹', 'Dog': '멍멍', 'Tiger': '어흥'}

In [2]:
for item in cage.?(): # values + keys = items
    print(item)

('Cat', '야옹')
('Dog', '멍멍')
('Tiger', '어흥')


In [ ]:
# 숫자들의 리스트에서 1과 4가 연속으로 나오는 숫자 찾기

list_of_nums = [121142131512315, 1241561717265467, 153462615114151231, 1634263414616123, 15236172821568]
for ? in ?:
    if ? in ?(num):
        print(num)

In [ ]:
?(5) # '범위'를 영어로?

In [98]:
for index in ?(5):
    print(index)

0
1
2
3
4


In [8]:
class = ['철수', '영희', '동수'] # 왜 에러가 발생할까요?

SyntaxError: invalid syntax (<ipython-input-8-472c712a4835>, line 1)

In [ ]:
for student in class_1:
    print("얘 이름은 {}래요".format(student))

In [8]:
# enumerate 배우기

for index, student in enumerate(class_1):
    print("얘 번호는 {}번이구요. 이름은 {}래요".format(index, student))

얘 번호는 0번이구요. 이름은 철수래요
얘 번호는 1번이구요. 이름은 영희래요
얘 번호는 2번이구요. 이름은 동수래요


In [9]:
# for 문의 주된 활용 방식

empty_list = []
for student in class_1:
    empty_list.?('김' + student) # 리스트에 item 추가하기

In [10]:
empty_list

['김철수', '김영희', '김동수']

In [3]:
sentence = 'This is the sample sentence. Sentence is comprised with words. Word is a group of charactors. NLP is short for Natural Language Programming. It covers the topics related with real words & sentences in language'
words = sentence.?().?(' ') # 전체 문장을 소문자로 치환 후, 여백(' ')을 기준으로 나눠서 list로 저장 
print(words)

['this', 'is', 'the', 'sample', 'sentence.', 'sentence', 'is', 'comprised', 'with', 'words.', 'word', 'is', 'a', 'group', 'of', 'charactors.', 'nlp', 'is', 'short', 'for', 'natural', 'language', 'programming.', 'it', 'covers', 'the', 'topics', 'related', 'with', 'real', 'words', '&', 'sentences', 'in', 'language']


#### while

In [106]:
temp = 1
while temp <= 10:
    print(temp)
    temp = ? + 1 # temp 를 1 증가시켜주려면?

1
2
3
4
5
6
7
8
9
10


In [107]:
# 무한 루프, Pass, Interrupting kernel

while True:
    pass

KeyboardInterrupt: 

In [1]:
idx = 0
while True:
    if idx >= 5:
        break
    else:
        print(idx)
        idx += 1

0
1
2
3
4


In [2]:
idx = 0
while 1:
    if idx >= 5:
        break
    else:
        print(idx)
        idx += 1

0
1
2
3
4


In [212]:
# Quiz 4. 점수(0~100)를 입력으로 받아 학점을 출력해주는 함수 grade를 만드세요.

In [215]:
grade(87)

B


In [216]:
# Quiz 5. 3개의 숫자를 입력으로 받아, 가장 큰 수를 출력하는 함수 best 를 만드세요. (Hint. 리스트와 sort()를 활용해보세요.)

In [242]:
best(20, 100, 60)

100


In [251]:
# Quiz 6. 숫자 하나를 입력받아, 홀수면 "odd", 짝수면 "even"을 출력하는 함수 odd_or_even을 만드세요. (나머지 연산 명령어는?)

In [253]:
odd_or_even(9)

odd


In [254]:
# Quiz 7. "20180323sunny" 와 같은 문자열을 입력받아, "Year is 2018, Day is 0323, Weather is sunny" 를 출력하는 함수 weather를 만드세요.

In [256]:
weather('20180323still cold')

Year is 2018, Day is 0323, Weather is still cold


<br>
<br>

# <b style='color:gray;'>PAUSE</b>

<br>
<br>

<br>

#### 5. 파일 읽고 쓰기

#### 파일 쓰기

In [108]:
file = ?('cage.txt', 'w', encoding='utf-8') # '열다'를 영어로? & w/r/a

In [109]:
cage = ['Cat', 'Dog', 'Tiger']

In [110]:
file.write(cage) # 에러가 발생했어요. 어떻게 해야할까요?

TypeError: write() argument must be str, not list

In [112]:
file.?() # open & write & close

In [ ]:
# close를 안쓰려면?


In [114]:
# file.write(cage) 대신,
file = ?('cage.txt', 'w', encoding='utf-8') # '열다'를 영어로? & w/r/a

for animal in cage:
    file.write(animal + '\n') # \t 로 바꿔서도 실행해보세요
    
file.close()

In [ ]:
# file = open('cage.txt', 'w', encoding='utf-8')
# file.writelines(cage)
# file.close()

In [116]:
# 자동으로 파일 닫기 (convention)

? open('cage.txt', 'w', encoding='utf-8') as file: # '함께', '~와 같이' 를 영어로?
    for animal in cage:
        file.write(animal + '\n')

#### 파일 읽기

In [117]:
file = open('cage.txt', ?, encoding='utf-8') # 읽기 모드

In [ ]:
cage = file.?() # 여러줄 한번에 읽어서 리스트에 담기 (Shift+Tap 을 사용해보세요!)
cage

In [ ]:
print(cage[0])

<br>

#### 6. Python 기본 내장함수와 외장함수

In [311]:
?('Python') # 길이?

6

In [312]:
list('Python')

['P', 'y', 't', 'h', 'o', 'n']

In [313]:
?(-1.2) # '절대값'의 앞 3글자

1.2

In [322]:
?(1.7) # 반올림

2

In [314]:
?(1) # 참/거짓 판별

True

In [317]:
?([1, 2, 3]) # 합

6

In [318]:
?([1, 2, 3]) # 최대값

3

In [319]:
?([1, 2, 3]) # 최소값

1

In [144]:
def func(x):
    return x**2

In [145]:
func(5)

25

In [323]:
# x(input) 를 받아 x**2(output) 를 return 해주는 람다 함수



In [324]:
func(5)

25

<br>

#### 7. 라이브러리 활용하기 (Library == Package, Module(단일 .py)의 상위 개념 )

In [20]:
%%writefile module_example.py

# @ module_example.py

def print_something() : 
    print('Hello world!')

def sum_nums(num1, num2) : 
    result = num1 + num2
    return result

Writing module_example.py


In [17]:
# %ls module_example.py

In [1]:
import module_example

module_example.print_something()

Hello world!


In [337]:
import numpy # import 라이브러리이름

In [338]:
a = numpy.array([1, 2, 3])
a

array([1, 2, 3])

In [339]:
import numpy as np # import 라이브러리이름 as 별명

In [340]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [343]:
from numpy import array, ndarray # from 라이브러리이름 import 함수이름

In [342]:
a = array([1, 2, 3])
a

array([1, 2, 3])

In [325]:
import random # 외장함수

x = random.random()
x

0.10961064046566416

In [326]:
x = random.?(1, 100) # 1과 100 사이의 '정수' 를 랜덤하게 뽑으려면? Shift + Tab 을 활용해보세요!
x

7

In [20]:
import os # 외장함수

os.getcwd() # get current working directory

#### pip 명령어 살펴보기 : pip + [ list/freeze/check, show/install/uninstall library_name, search search_keyword ]

In [ ]:
# cmd 에서 입력해 결과를 확인해보세요.

pip list
pip freeze > lib_list.txt
pip check

pip show numpy
pip install numpy (주의)
pip uninstall numpy (주의)

pip search xgboost